MiniDeps.later(function()
    local mini_keymap = require("mini.keymap")
    mini_keymap.setup({})
    mini_keymap.map_multistep('i', "<Tab>", {"pmenu_next", "minisnippets_next", "minisnippets_expand"})
    mini_keymap.map_multistep('i', "<S-Tab>", {"pmenu_prev", "minisnippets_prev"})
    mini_keymap.map_multistep('i', "<CR>", {"pmenu_accept", "minipairs_cr"})
    mini_keymap.map_multistep('i', "<BS>", {"minipairs_bs"})
    mini_keymap.map_combo({'i', 'c'}, "jk", "<BS><BS><Esc>")
    mini_keymap.map_combo({'i', 'c'}, "kj", "<BS><BS><Esc>")
    mini_keymap.map_combo('t', "jk", "<BS><BS><C-\\><C-n>")
    mini_keymap.map_combo('t', "kj", "<BS><BS><C-\\><C-n>")
end)
