[package]
name = "menu"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
gtk4 = { workspace = true }
libadwaita = { workspace = true }
component = { path = "crates/component" }
applications = { path = "crates/applications" }
audio = { path = "crates/audio" }
bluetooth = { path = "crates/bluetooth" }
clipboard = { path = "crates/clipboard" }
macros = { path = "crates/macros" }
power = { path = "crates/power" }
soundboard = { path = "crates/soundboard" }
network = { path = "crates/network" }

[workspace]
resolver = "3"
members = [
    "crates/component",
    "crates/applications",
    "crates/audio",
    "crates/bluetooth",
    "crates/clipboard",
    "crates/macros",
    "crates/power",
    "crates/soundboard",
    "crates/network",
]

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
gtk4 = { version = "0.11", package = "gtk4", features = ["v4_12"] }
libadwaita = { version = "0.9", features = ["v1_7"] }
