require("configs.mini")
require("configs.config-options")
require("configs.config-highlight")
require("configs.config-keymaps")
require("configs.config-autocmds")
require("configs.config-usercmds")
require("configs.config-lsp")
